{{ if .Values.secretStore.fake }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fakeopserversecretstore
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  provider:
    fake:
      data:
      - key: "ExceptionsSqlServerName"
        value: "host.docker.internal"
      - key: "db-opserver-User"
        value: "opserver"
      - key: "db-opserver-Password"
        value: "opserver"
{{ end }}
