{{ if .Values.secretStore.fake }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fakeopserversecretstore
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  provider:
    fake:
      data:
      - key: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusSqlServerName }}
        value: "host.docker.internal"
      - key: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusUsername }}
        value: "opserver"
      - key: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusPassword }}
        value: "opserver"
      - key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalServerName }}
        value: "host.docker.internal"
      - key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalUsername }}
        value: "opserver"
      - key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalPassword }}
        value: "opserver"
{{ end }}
