apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.configSecret.name }}
spec:
  refreshInterval: {{ .Values.configSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.configSecret.storeRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.configSecret.targetName }}
  data:
  - secretKey: ElasticSettings.json
    remoteRef:
      key: {{ .Values.configSecret.remoteRefs.ElasticSettings }}
  - secretKey: RedisSettings.json
    remoteRef:
      key: {{ .Values.configSecret.remoteRefs.RedisSettings }}
  - secretKey: SQLSettings.json
    remoteRef:
      key: {{ .Values.configSecret.remoteRefs.SQLSettings }}
