apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.opserverSecret.name }}
spec:
  refreshInterval: {{ .Values.opserverSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.opserverSecret.storeRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.opserverSecret.targetName }}
  data:
  - secretKey: oktaClientId
    remoteRef:
      key: {{ .Values.opserverSecret.remoteRefs.oktaClientId }}
  - secretKey: oktaClientSecret
    remoteRef:
      key: {{ .Values.opserverSecret.remoteRefs.oktaClientSecret }}
