apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
spec:
  selector:
    service: {{ .Release.Name }}
  ports:
  - name: "80"
    port: 80
    targetPort: {{ .Values.kestrel.endPoints.http.containerPort }}
