apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.sqlExternalSecret.name }}
spec:
  refreshInterval: {{ .Values.sqlExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.sqlExternalSecret.storeRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.sqlExternalSecret.targetName }}
  data:
  # These secrets are used by the Sql module of OpServer
  - secretKey: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusSqlServerName }}
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusSqlServerName }}
  - secretKey: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusUsername }}
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusUsername }}
  - secretKey: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusPassword }}
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.sqlStatusPassword }}
  # These secrets are used for the Exceptional module of OpServer 
  - secretKey: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalServerName }}
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalServerName }}
  - secretKey: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalUsername }}
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalUsername }}
  - secretKey: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalPassword }}
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalPassword }}
