apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.sqlExternalSecret.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  refreshInterval: {{ .Values.sqlExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.sqlExternalSecret.storeRefName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.sqlExternalSecret.targetName }}
  data:
  - secretKey: exceptionalServername
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalServerName }}
  - secretKey: exceptionalUsername
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalUsername }}
  - secretKey: exceptionalPassword
    remoteRef:
      key: {{ .Values.sqlExternalSecret.remoteRefs.exceptionalPassword }}
