name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/checkout@v4
    - name: Build with dotnet
      run: dotnet build
